include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false


analyzer:
  plugins:
    - custom_lint


custom_lint:
  rules:
    - avoid_if_with_enum:
      cool: true
      super_cool: obviously

