include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false


analyzer:
  plugins:
    - custom_lint
  errors: 
    avoid_string_literals_inside_widget: error


