name: example
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  bloc: 
  flutter:
    sdk: flutter
  flutter_bloc: 
  flutter_localizations:
    sdk: flutter
  intl:

dev_dependencies:
  bloc_test: 
  custom_lint:
  flutter_sane_lints:
    path: ../
  flutter_test:
    sdk: flutter
  mocktail: 
  very_good_analysis: 

flutter:
  uses-material-design: true
  generate: true
