name: flutter_sane_lints
description: A custom lint for flutter projects to avoid ad-hoc string literals.
version: 0.3.0
repository: https://github.com/gbassisp/extra_lints

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dev_dependencies:
  # build_runner: ^2.0.0
  coverage: ^1.11.1
  mockito: ^5.4.5
  mocktail: ^1.0.4
  test: ^1.0.0
  very_good_analysis: 

dependencies:
  analyzer: ^6.11.0
  custom_lint_builder: ^0.5.0
  meta: ^1.0.0