name: extra_lints
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.4
  flutter:
    sdk: flutter
  mockito: ^5.4.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0

dependencies:
  analyzer: ^5.10.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.3.3
  source_gen: ^1.3.2
